language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t domaxas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true domaxas/docker-react npm run test -- --coverage

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: docker-react
#  env: "Docker-react-env"
#  bucket_name: "name"
#  bucket_path: "path"
#  on:
#    branch: master